<?php

/**
 * implement hook_block_info()
 */
function sse_noticefilter_block_info() {
  $blocks = [];
  $blocks['notice_filter_block']['info'] = t('SSE: 通知筛选区块');
  $blocks['notice_filter_block']['cache'] = DRUPAL_NO_CACHE;
  return $blocks;
}

/**
 * implement hook_block_view()
 */
function sse_noticefilter_block_view($delta = '') {
  if ($delta === 'notice_filter_block') {
    $block = [];
    $block['subject'] = t('通知筛选');
    $block['content'] = theme('notice_filter_block', [
      'filters' => _sse_noticefilter_get_filters()
    ]);
    return $block;
  }
}

/**
 * 获取过滤术语
 */
function _sse_noticefilter_get_filters() {
  $filters = [];
  $filters[] = _sse_noticefilter_get_filter('target', 'notice_target');
  $filters[] = _sse_noticefilter_get_filter('category', 'notice_category');
  return $filters;
}

function _sse_noticefilter_get_filter($meta, $taxonomy_name) {
  $data = sse_util_get_nested_taxonomy_tree($taxonomy_name, true);
  return [
    'title' => $data['vocabulary']->name,
    'meta' => $meta,
    'tree' => $data['tree']
  ];
}
